apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
#      volumes:
#        - name: mysql-storage
#          persistentVolumeClaim:
#            claimName: mysql-pvc
      containers:
      - name: mysql
        image: adityahub2255/mysql:$DOCKER_TAG
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootpassword
          - name: MYSQL_DATABASE
            value: admin
          - name: MYSQL_USER
            value: gaetan
          - name: MYSQL_PASSWORD
            value: admin
        ports:
        - containerPort: 3306
#        volumeMounts:
#          - name: mysql-storage
#            mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None # Headless service to expose MySQL for internal access
